### ISSUE TITLE
Performance: fuse strategies where possible

### ISSUE THREAD

**Issue by Zac-HD** [maximkulkin/hypothesis-regex#5]
Creating strategies and extracting values from them is relatively expensive, and literal values are a decent chunk of most regular expressions.  

- [x] merge adjacent literal characters into one strategy (in #6)

Honestly I think that's already gained us most of the performance benefits, but there are some other places where we might be able to fuse strategies if you're interested:

- [ ] when a repeated pattern is entirely literal, it can be expressed as multiplying a string; when the at_least and at_most range are identical we can calculate that when constructing the strategy
- [ ] several codes translate to `hs.just(...)`, and these could be fused with adjacent literals
- [ ] groups of one character are equivalent to a literal for our purposes

I think the key for much of this is that Hypothesis actually reduces things to `JustStrategy(value)` wherever it can, so this could be implemented by adding a post-construction pass that unwraps and fuses strategies.  Essentially we'd be taking advantage of the fact that we know all the sub-strategies generate strings which will be concatenated.  This may well be reaching too far into the Hypothesis internals to be worthwhile at the moment - and may actually lead to some internal changes in strategy fusion - so I suggest merging upstream first, and either of us can look at it again after that.

**Comment by maximkulkin** [comment]
Yeah, I'm aware of possibility to merge static consequent literals (as long as IGNORECASE is not enabled) and something I was definitely was going to do at some point.

Not sure I understand how generating groups upfront can help performance wise and how is this different to using tuple and then merging all results together.

**Comment by Zac-HD** [comment]
Nice.  On further reading it looks like the groups advice is inapplicable, and your approach with tuples is nicer anyway.

**Comment by maximkulkin** [comment]
@Zac-HD you mentioned that merging literals is not enough. Could you outline other cases?

**Comment by Zac-HD** [comment]
I was actually just in the middle of investigating that!  It looks like the best way to do further fusion is actually *after* the strategy has been constructed.  However, as noted above, this is best done internally in Hypothesis - so I'll close this issue.
